### ISSUE TITLE
AC:   we understand what data to collect on the new Volunteer screen

### ISSUE THREAD

**Issue by sppatel75** [NorthBridge/nexus-community#103]

**Comment by kdflint** [comment]
The new volunteer application screen shall include these items:

* A place for user to describe what their personal motivation for volunteering (such as "get leadership experience", "get experience with Java", "network", etc.)

* A place for user to identify their general background (testing, coding, analysis, etc.)

* A place for user to describe their skills in more detail ( probably free text)

**Comment by kdflint** [comment]
This screen will also have a link to the current Playbook and calendar for general Northbridge orientation sessions

**Comment by kdflint** [comment]
![screenshot from 2015-01-27 20 27 10](https://cloud.githubusercontent.com/assets/1907202/5931399/2070b6c8-a663-11e4-8f4c-cc71ec16e348.png)

**Comment by kdflint** [comment]
missing Submit button

**Comment by sppatel75** [comment]
Screen looks good, one comment:  "Your email, please", should be just "Email".  Folks will know that email is required to get communications.

**Comment by kdflint** [comment]
add confirm email box

**Comment by sppatel75** [comment]
Closing
