### ISSUE TITLE
AC: we understand business flow for new applications

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#105]
As discussed in 1/22 standup:

* Initial applications will be emailed to coaches email list.

* Data that is captured will include follow-up status, contact info., etc.

* In general, coaches are responsible for matching volunteers to teams.

* In future we will create an admin site, probably leveraging the current site that is called "Alliance" which has several tools and a database in place behind it. (Open question: how best to leverage Nexus capabilities? Shift to Nexus altogether or plug in Nexus components to Alliance?)

**Comment by sppatel75** [comment]
close
