### ISSUE TITLE
AC: The coaches receive an email when a new volunteer signs up.

### ISSUE THREAD

**Issue by sppatel75** [NorthBridge/nexus-community#112]

**Comment by kdflint** [comment]
For now, this is going to have to go through me. I will get notice of new volunteer submission, query from db, and then forward volunteer info to coaches list.

It would take me almost as long to pull the volunteer data into the email as it will to just build the simple admin interface. (Message creation is asynchronous so I have to query db anyway...) So, if we can live this email situation just a few weeks then we'll jump right to the admin screen solution.

Ok??

**Comment by sppatel75** [comment]
For now, automated email will go to Kathy, and Kathy will run a query and send email to coaches.  Closing this issue.
