### ISSUE TITLE
AC: Page load shows download speed

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#114]

**Comment by kdflint** [comment]
Implementation is done. Some code review and testing would be lovely.

**Comment by gretchiesprite** [comment]
I tested this on my computer and my phone and it works well for me. I got green light and the download speed on my computer every time (most of my download speeds were 200 Mbps and up). On my phone I got a red light once when the download speed was 2 Mbps and a green light when it was over 30.

**Comment by kdflint** [comment]
Thx Gretchen! Closing now.
