### ISSUE TITLE
AC: Login screen

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#149]
Functionality includes:

1. Data input validation (front end)

2. Remember me functionality - (when box is checked, session will not time out and will be restored after a window close event)

3. Session timeout if session not remembered - five minutes in dev testing

4. Forgot username

5. Forgot password

Functionality excludes:

User profile edit form functionality. This form works just well enough to let you reset a password.

**Comment by gretchiesprite** [comment]
When resetting the password, is the user supposed to see the letters/numbers/characters they are typing, or do we want to have dots (or similar) for the characters? 
![screen shot 2015-07-30 at 3 29 33 pm](https://cloud.githubusercontent.com/assets/2071968/8994344/4af26e7a-36d0-11e5-8574-8264b7a48f92.png)

**Comment by northbridge-test** [comment]
I left those fields readable just for the moment for testing convenience.

When we get to actual testing on this form, we will hide those characters
for sure.



-- 



*Kathy Flint, CEO Northbridge Technology Alliance
http://northbridgetech.org
<http://NorthBridgeTech.org>kathy.flint@northbridgetech.org
<kathy.flint@northbridgetech.org> *

**Comment by kcavness** [comment]
![image](https://cloud.githubusercontent.com/assets/5615067/9020005/c14f2f40-37ac-11e5-9ba0-70e273d801ab.png)

I see we can include images! That is very useful.

Note that I was able to change the URL error variable's contents to change the error message. If possible and we can return this as a POST operation, that might be better.

**Comment by kcavness** [comment]
FYI -- I have tested using the emulation going all the way back to IE6 and ... I don't trust the emulation, because it works in there too, and ... well, if anyone can find IE6 or an emulation tool that will allow me to test this in a way I trust, we should do that. Otherwise, we appear to be good for all versions of IE -- the problems I'm identifying APPEAR to be global (except perhaps "Remember me").

This may be because we're using JQuery for the site.

**Comment by kcavness** [comment]
My testing spreadsheet can be found here.

https://docs.google.com/spreadsheets/d/1BLdgnO6JnZ0NS3uYsKlvUSY3c8UC53X0yosAxT40EFQ/edit?usp=sharing

**Comment by gretchiesprite** [comment]
On the login screen, I am unable to successfully check the "remember me" box if I click on the check box itself it Safari, Chrome, and Firefox. When I click on the check box, a dark outline appears at the edges of the button. If i click the text "remember me" then the check box does fill with a check mark.

**Comment by kdflint** [comment]
Hey Kenneth - check this tool for browser emulation: https://www.browserstack.com

You can get 30 minutes free, which I have used just to do sanity checking. Might be useful if you don't totally trust your emulation.

**Comment by kcavness** [comment]
Thanks Kathy! That's basically perfect, as I can test with IE6 and just make sure that the emulation is correct and JQuery is doing all the right stuff.
