### ISSUE TITLE
AC: Add meeting room reservation

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#152]

**Comment by gretchiesprite** [comment]
In Safari, the Date field is not lined up with the Time and Duration fields. Also, the New Reservation box overlaps with the box containing the scheduled meetings.
![screen shot 2015-08-04 at 8 14 19 pm](https://cloud.githubusercontent.com/assets/2071968/9076245/97f1308a-3ae5-11e5-94ae-bc98cbb47e96.png)

**Comment by kdflint** [comment]
Well, ok, I fixed one thing that is shown above but that you did not describe. The overlap on the New Reservation box and Upcoming Meetings section is gone (I hope). You should see 5 pixels of white space between the two sections.

Still looking at the problem you actually did describe :)
