### ISSUE TITLE
Login Page - Incorrect username validation message in username field

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#156]
![image](https://cloud.githubusercontent.com/assets/5615067/9020069/05422cb4-37af-11e5-8c8e-191a82e37851.png)

Says "Username name is required" -- extra word in error.

**Comment by kcavness** [comment]
This same error validation issue happens when you choose "Reset Password" without entering a username on "I Forgot" by the password field.

**Comment by kdflint** [comment]
Fixed in both places places.

**Comment by kcavness** [comment]
Error message is now correct correct.
