### ISSUE TITLE
Login Remember Me check box funk

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#160]
From Gretchen - On the login screen, I am unable to successfully check the "remember me" box if I click on the check box itself it Safari, Chrome, and Firefox. When I click on the check box, a dark outline appears at the edges of the button. If i click the text "remember me" then the check box does fill with a check mark.

**Comment by kdflint** [comment]
Before the fix, the actual form checkbox was positioned inside a styled anchor.

Now the actual form checkbox is visibility:hidden and the user experiences an image toggle. 

Unchanged is that the anchor onclick event toggles the actual checkbox value using javascript and this is what the processor reads.

**Comment by gretchiesprite** [comment]
This works, closing.
