### ISSUE TITLE
Internet Explorer: Dropdown elements look different for Timezone dropdowns than for other elements in Room Reservation if "Reserve" clicked on before choosing them

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#161]
The look-and-feel of the dropdown elements for Timezone dropdowns is different (Perhaps default?) from the look-and-feel of other dropdown elements in the Room Reservation section.

**Comment by kcavness** [comment]
Sorry, I'm incorrect about this. Not sure how to delete an error, but this is not true. I was mistaking a validation look-and-feel with the usual dropdown looks.

HOWEVER, if I click on "Reserve" I don't show validations to choose a country and time zone. I will update issue to reflect this.

**Comment by kcavness** [comment]
![image](https://cloud.githubusercontent.com/assets/5615067/9156938/40c7a65a-3e9f-11e5-92d3-34bd3fb374a4.png)

**Comment by kdflint** [comment]
Now the time zone change fields will show fail validation (with correct styling) if the user has not finished their Change operation.

Note: The Country field will revert to "no value selected" in the case where the user selects a country but leaves the time zone unselected.

**Comment by kcavness** [comment]
In IE at least, the date field is still slightly smaller in look than the other fields; I'm really not sure if this is important, though. 

![image](https://cloud.githubusercontent.com/assets/5615067/9619332/eb5bc778-50c3-11e5-82f8-b9d5369459d5.png)

**Comment by kdflint** [comment]
Smaller date field covered by #162 . If time zone validation looks good, this can Close.
