### ISSUE TITLE
Times entered in the past that intersect, by duration, with the current time, do not show up in room reservations

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#164]
If a meeting is created for the current date but in the past, with a duration that would cause it to still be going on right now, it does not show up in the room reservation list and no error is generated. Since we do not allow exact times in the "time" dropdown, this makes it very tough to create a meeting that should be happening "now".

**Comment by kdflint** [comment]
By taking away the possibility to create meetings in the future (#163) and with the addition of the new Open Room Now functionality, is this use case covered?

Seems like it might be but I am getting date/time woozy...

**Comment by kcavness** [comment]
I now get an error message saying "Your meeting time is in the past", which is a valid response from the application. Closing.
