### ISSUE TITLE
Entering an invalid date in the text field for dates rather than selecting from the calendar displays a technical error

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#165]
I created a room reservation with all elements other than date entered correctly. Instead of choosing a date from the calendar that popped up, I entered one into the textbox directly in an invalid format (I used YYYY-MM-DD. I received a PHP nastygram.

Array ( [clean] => Array ( [meeting-name] => Kenneth Room Reservation Test 5 [tzone-name] => America/Los_Angeles [meeting-time] => 06:30:00 [meeting-duration] => 01:30:00 ) [error] => Array ( [meeting-date] => error ) )

**Comment by kcavness** [comment]
![image](https://cloud.githubusercontent.com/assets/5615067/9156882/d691643e-3e9d-11e5-84be-b92a04cbc022.png)

**Comment by kdflint** [comment]
Stated issue is fixed. I was mishandling javascript regex.

Also now it will error if you have too many days in a month, including leap years through 2032. (for example, 04/31/2015 and 02/29/2015 did not fail before but now do.)
