### ISSUE TITLE
Email link to login screen using org id instaed of org uuid

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#167]
Invite a user, then enroll that user from the email invitation.

The enrollment confirmation has a link to Nexus. This link has an `oid` parameter with a value that is only 3 digits long. Example:

http://northbridgetech.org/dev/new_nexus/web/login.php?oid=330

This is the wrong id. It should be reflecting the organization's 8-digit uid.

**Comment by kdflint** [comment]
Now the link will have an 8-digit value for the `oid` query parameter.

For the development test organization, the link will look exactly like 

http://northbridgetech.org/dev/new_nexus/web/login.php?oid=12345678

**Comment by kcavness** [comment]
Now reflects the correct value. However, the OID field now shows as "invitation" -- I assume this is intended?

http://northbridgetech.org/dev/new_nexus/web/enroll.php?invitation=b21cd16c-6bb4-b581-d6e0-e2f050626070
