### ISSUE TITLE
Missing enrolled users on Team page

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#169]
The existing / pending users list on the Team tab isn't displaying all the users any more, and seems to be ending after three users I managed to add that I shouldn't have been able to add. I added a valid user after this, but it isn't showing up on the list either. Logging out and logging back in didn't seem to help.

While testing, I entered nothing in the "First Name" field and a valid email and clicked "Enroll". At first it provided me a validation error, but then it sent me back to the Room Page and suddenly I received an enroll email for all three times I tried it -- each for a different "user" that had the same email but no first name, because I tried it three times trying to figure out exactly where the issue lie. The emails said (note the lack of name: )

Hello ,

You have been added to the team.

Follow this link to complete your enrollment:

http://northbridgetech.org/dev/new_nexus/web/enroll.php?invitation=a7f1c64d-b3d2-d92c-3ab5-858313d58965

The Support Team at
NorthBridge Technology Alliance

**Comment by kdflint** [comment]
Now Kenneth, you know as well as I do that it's ALWAYS the coders fault!

Munching two query results sets into one indexed array, I restarted the array counter back at zero. 

Duh.

Now all Pendings should show at top of list ordered by email address, and all Enrolled at bottom ordered by first name.

I am not limiting the size of the list because in this first rollout, these groups are limited to 10 people. (This limit is not implemented yet.)

Kathy

**Comment by kcavness** [comment]
After doing...whatever it was...that you did, it seems to work now! (Plus, I was able to enroll/delete the weird users :) )
