### ISSUE TITLE
Limit size of group to 10

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#170]
Only 10 people should be able to be enrolled per group. (That is, per oid)

After 10 enrollments, disappear the icon and show a notice that max has been reached.

**Comment by kdflint** [comment]
After 10 enrollments/invitations, the user add icon disappears, but no message. OK, for now - will do something more elegant soon. (#185)

**Comment by gretchiesprite** [comment]
This works, closing. I noticed that I can send multiple invites to the same email account. Not sure if that's something we want to address. If so, I can open up a new issue.

**Comment by kdflint** [comment]
This is considered legal, for now at least.

For the record, in Nexus we do not treat email address as a unique account
identifier and we allow multiple accounts to share a single email address.
This might change but for now I like the freedoms this open up.

-- 



*Kathy Flint, CEO Northbridge Technology Alliance
http://northbridgetech.org
<http://NorthBridgeTech.org>kathy.flint@northbridgetech.org
<kathy.flint@northbridgetech.org> *
