### ISSUE TITLE
Adding user without a first name currently adds the user

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#171]
I added a user by entering a valid email in the email field but nothing in the First Name field, and instead of preventing me from enrolling the user, the system after a short delay added the user with a blank first name. The email I was sent didn't handle this well, either, saying "Hello ," The new user with a blank first name then appeared in the list of pending users.

**Comment by kdflint** [comment]
Now one will either see

Hello fname, OR Hello, NEVER Hello ,

**Comment by gretchiesprite** [comment]
Works, closing.
