### ISSUE TITLE
After adding a user or deleting a user, sent back to "Room" page instead of "Team" page

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#172]
After performing an action in the "Team" page successfully including adding a user or deleting a user, I am sent back to the "Room" page instead of the "Team" page. I would expect intuitively to be sent back to the "Team" page.

**Comment by kdflint** [comment]
Fixed: Not in a very scalable way but will do for now. (A view parameter on the request string causes a script to "click" the Team button and load the correct page view.)

The user list view is now invoked when you add or delete a user.

**Comment by kcavness** [comment]
I am being sent back to the correct room now.
