### ISSUE TITLE
Adding a user with a long first name breaks look-and-feel of team page

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#173]
The newly created user's name continues past the section column line.

**Comment by kcavness** [comment]
![image](https://cloud.githubusercontent.com/assets/5615067/9239998/7c61c082-4116-11e5-84c3-2c4aa18eecc7.png)

**Comment by kdflint** [comment]
Now the display should accommodate first names of length up to 15. (Solution: font size decreases as name length increases using dynamic styling.)

After that, not sure what to do... truncate? Say oh well? At that length we also start to hit problems in the "Hello <name>" under the logout link.

Suggestions welcome!

Ideas?

**Comment by kdflint** [comment]
Has this passed anywhere?

**Comment by kcavness** [comment]
I tried with a 15-character name, and it doesn't mess up the look and feel any more, but it ALSO doesn't really match the look and feel of everything else. I understand that the font size decreases, but maybe a bolding or somesuch should be used So that look-and-feel is maintained?

![image](https://cloud.githubusercontent.com/assets/5615067/10716912/40b4bc00-7b05-11e5-9590-87da029dfa26.png)

Even sixteen character names looks fine too.

![image](https://cloud.githubusercontent.com/assets/5615067/10716935/9e44f4e8-7b05-11e5-8492-fc21ee93bf8a.png)

**Comment by gretchiesprite** [comment]
I noticed that with a really long name, the look and feel the name does continue past the section column line. This is from Chrome.

**Comment by kcavness** [comment]
Yes, though I think you get what you deserve if you have a 25 character
long name :p

(Some Indian names can reach pretty long, though!)

I do see GretchenIsAwesome humbly extending past the line, though. I think
the only way to prevent this for truly insanely long names would be to set
word break accordingly in CSS, though that may mess with the gloriosity of
the current design.

**Comment by kdflint** [comment]
Opened a new issue (#209) to play with bolding and see if we like it better.

Sometimes extending past the line is just the price one pays for awesomeness...
