### ISSUE TITLE
Add the end times for meetings that are running Now or Soon

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#175]
Now and Soon as interpreted in the display logic in reservationsList.html

**Comment by kdflint** [comment]
To test: In NWM

1. Enter a meeting running now, for some duration. Check that the output shows the end time accurately.

2. Enter a meeting for the future. Once the time approaches Soon or Now, check the the output shows the end time accurately.

**Comment by gretchiesprite** [comment]
Works, closing.
