### ISSUE TITLE
On Team Page user list, show Username

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#179]
We have enough room to supply a little more information, and I think supplying the user's username in the list of users might be useful info. (Especially for testing!)

**Comment by kdflint** [comment]
Started to do this, but then wondered... is it a good idea to show usernames for the whole team to the whole team? (security?)

Maybe show only to this session user? Or put it in the profile instead?

**Comment by kdflint** [comment]
fyi - In Advantage, this equivalent screen will show more, like allow you to message another user, see their directory listing, etc.

For this simple app, thoughts on what else would be good here... maybe last login? Whatever we add here probably has to be collected in the profile...

**Comment by kdflint** [comment]
After discussion, we have decided that the problem we were trying to address by adding the username to the display is now solved another way. So, will make no change.
