### ISSUE TITLE
On Team Page, unrelated area of page can open new user dialog

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#180]
I have the ability to click on the first user's first name or their email address and have it open the "new user" dialog; I would expect only the "new user" icon to be able to make this happen.

**Comment by kdflint** [comment]
Ha - a wonderful illustration of the difference between css padding and margin

Now these elements are all placed using a margin-left attribute which puts all that space to the left outside of the anchor's control. 

Prior they used a padding-left which put that area INSIDE inside the anchor's control

**Comment by gretchiesprite** [comment]
Works, closing.
