### ISSUE TITLE
In Enrollment Confirmation Email, deleted users show up in list of existing users with same email

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#181]
None of the users still exist even though shown in this email (or, at least, they have been deleted):

![image](https://cloud.githubusercontent.com/assets/5615067/9619684/6424e93e-50c7-11e5-9fa4-823e8ce5e4a5.png)

**Comment by kdflint** [comment]
eep ... where status = 'active'

fyi - under that email address you now have 9 suspended and 1 active user. If you enroll another user with 'kenneth.cavness.gmail.com' I would expect your enrollment confirmation to show now one additional username, not 10.

**Comment by gretchiesprite** [comment]
This works for me now. Closing.
