### ISSUE TITLE
In Self User Profile, change Cancel link to Reset

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#182]
Elsewhere in the functionality, "Cancel" means "Disappear the dialog", but "Cancel" resets the fields in the user profile section. This would be better worded as "reset".

**Comment by kdflint** [comment]
I took the easy route and just changed the label to "Reset" as you suggest.

Maybe it actually should minimize too but I"ll leave it be for now.

**Comment by gretchiesprite** [comment]
Works, closing.
