### ISSUE TITLE
Reset password link does not reveal password reset form

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#192]
Just logs the user into the site with no indication of what to do next.

**Comment by northbridge-test** [comment]
Also double check that "remember me" is cancelled out if set

-- 



*Kathy Flint, CEO Northbridge Technology Alliance
http://northbridgetech.org
<http://NorthBridgeTech.org>kathy.flint@northbridgetech.org
<kathy.flint@northbridgetech.org> *
