### ISSUE TITLE
AC - New Video Link meeting type optin

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#194]
Selecting the Video Link option for a meeting configuration causes the meeting room to open with no audio option. (User should be able to share camera, see presentation, chat, etc.)

The purpose of this configuration is to allow a centralized meeting to leverage their phone bridge for audio and BigBlueButton to add a video feed to their meeting. (Remember the conference audio is not suitable for open air speakers...)

**Comment by kdflint** [comment]
Please regression test the other meeting types. There are three now.

**Comment by gretchiesprite** [comment]
Works for me in Safari, Firefox, and Chrome
![screen shot 2015-10-13 at 1 32 05 pm](https://cloud.githubusercontent.com/assets/2071968/10464377/225a09c2-71af-11e5-8b5f-3fc110a71f77.png)
. See attached spreadsheet for details.

**Comment by kdflint** [comment]
fyi - I removed the desktop share button from the video link configuration - the chart above alerted me on that. Thx Gretchen!
