### ISSUE TITLE
Nexus Web Meet timeout oid query param value incorrect

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#196]
Should show a message that indicates user session has timed out. Right now message says they logged out.

**Comment by kdflint** [comment]
To test, let a session timeout (5 minutes in dev) and then Ctrl-R to reload a page. You will get booted to the login screen.

If working properly you should see the correct logo and org name show up on the right and an 8-digit string for the oid parm value in the browser bar. (In dev, oid=12345678)

**Comment by gretchiesprite** [comment]
Works for me in Safari, Firefox, and Chrome.
