### ISSUE TITLE
Fonts on the top bar after logging out of conference room don't match fonts elsewhere

### ISSUE THREAD

**Issue by gretchiesprite** [NorthBridge/nexus-community#198]
See attached. The fonts for "Nexus Web Meet" on the page after logging out of the conference room do not match the fonts on the other pages of the site.
![screen shot 2015-10-13 at 12 54 05 pm](https://cloud.githubusercontent.com/assets/2071968/10463455/62a63564-71aa-11e5-9c61-0bfad2c6bf23.png)
![screen shot 2015-10-13 at 12 56 27 pm](https://cloud.githubusercontent.com/assets/2071968/10463456/62a68352-71aa-11e5-8a25-07e80f532ddf.png)

**Comment by kdflint** [comment]
Can you check this again, Gretchen? It looks ok here and it seems like it should be ok as the stylesheet link seems right... maybe you had a cached version of the style sheet?

**Comment by gretchiesprite** [comment]
Yeah, it looked correct after I cleared the cache. Closing.
