### ISSUE TITLE
Internet Explorer: Desktop Sharing does not work in IE (Video Chat Room)

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#205]
I attempted to share my desktop in Video Chat mode, and got the following error:

"Chrome no longer supports Java Applets. You must use a different web browser (Firefox recommended) to share your desktop."

This is probably true for IE as well, but this says Chrome. IT may be something with BigBlueButton that you can't change, but wanted to at least report it in case.

![image](https://github-cloud.s3.amazonaws.com/assets/5615067/10564977/ec5599e8-757a-11e5-9e30-ec60c9897c52.png)

**Comment by kdflint** [comment]
LOL

OK, the phenomenon with Chrome actually is only Chrome. IE still allows Java applets. But there is a different reason that I intended to hide the desktop share button, which now I have. It was already hidden in the other two meeting modes. I tested this myself and now am closing.
