### ISSUE TITLE
Unable to delete last user in team room list

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#208]
I for some reason am unable to delete the last user in my meeting room, even though I have verified that I am not logged in as that user and am an administrator, and I CAN delete all other users that I would have rights to delete if I so wished.

![image](https://cloud.githubusercontent.com/assets/5615067/10716949/e6172f5c-7b05-11e5-86b4-759e89a7d3da.png)

**Comment by gretchiesprite** [comment]
I made a user that started with a Z and was able to delete it in Chrome. Kenneth, do you mind if I try to delete your SixteenCharacter user?

**Comment by kcavness** [comment]
Go ahead!

**Comment by gretchiesprite** [comment]
Worked for me in Chrome.
![screen shot 2015-10-25 at 8 40 17 pm](https://cloud.githubusercontent.com/assets/2071968/10719533/a785843e-7b58-11e5-815f-23f97e8a8861.png)

**Comment by kcavness** [comment]
Hm. Let me see what happens in Edge when I try to delete Shannon (I won't
actually delete Shannon)

**Comment by kcavness** [comment]
Yep, unable to delete Shannon now. All other trashcans work, just the last
one. (Microsoft Edge)

**Comment by gretchiesprite** [comment]
I checked Safari and Firefox as well, and they're good.

**Comment by kdflint** [comment]
So in Safari and Firefox you can delete the last user but you can't in Edge?

I am leaving this open but moving it to a current milestone...

**Comment by kdflint** [comment]
OOOOOHHH, you mean literally the last user on the list, not where list.length == 1

Kenneth, let's chat on this on a standup.

**Comment by kdflint** [comment]
I fixed some badly formed html. It's all being dynamically generated by javascript on the ajax return - easy to screw up!

Kenneth - could you retest please?

**Comment by kcavness** [comment]
Just retested and it works fine now!
