### ISSUE TITLE
On Calendar Event Add, time zone field is not populating

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#217]
If I:
* Log in to Nexus Advantage
* Click on Calendar Tab
* Click on "Add event" icon
* Choose "Change" for time zone
* Enter any country where a time zone is expected to exist
* Click on the "Time Zone" dropdown

Then I expect to:
* See a list of time zones from which I can pick

Instead, what happens is:
* The time zone dropdown has no items in it.

I have tested this in Chrome and Microsoft Edge, and has the same behavior in both browsers

**Comment by kdflint** [comment]
Cannot reproduce at this time. Can you retest, Kenneth?

**Comment by kcavness** [comment]
I can no longer duplicate this, so closing it.
