### ISSUE TITLE
NWM - event add icon is above tooltip

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#225]
z-index is 10 on the event add icon, so it is appearing on top of meeting type tooltip when that is displayed, which is also z-indexed at 10.

**Comment by kdflint** [comment]
To test: In NWM, expand the Start a Meeting Now menu. Hover over information icon to see the Meeting Types tooltip. Confirm that the tooltip text covers everything else in its perimeter.

**Comment by gretchiesprite** [comment]
The new event icon is still above the info box in Safari and Firefox. I cleared the cache, but that didn't work.
<img width="785" alt="screen shot 2016-04-10 at 7 15 55 pm" src="https://cloud.githubusercontent.com/assets/2071968/14414025/cabbff60-ff50-11e5-82e2-1d1adb898c8e.png">

**Comment by kdflint** [comment]
I bet you're looking in Production, Gretchen. Can you double-check that you are logging in at

http://northbridgetech.org/dev/nexus/web/login.php

**Comment by gretchiesprite** [comment]
Looks good, closing!
