### ISSUE TITLE
Unable to add meeting for same day in the future

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#237]
I attempted to add a meeting for several hours in the future on the same day, but kept getting a Javascript dialog error telling me that the meeting occurred in the past.

**Comment by kdflint** [comment]
Just created a meeting at 1:20 PM 
![screenshot from 2016-01-31 13 20 25](https://cloud.githubusercontent.com/assets/1907202/12704302/89ecb4d0-c81d-11e5-8af2-3c578afcc353.png)
CST for same day at 4:00 PM CST

**Comment by kdflint** [comment]
IE12/Edge, seems to work ok too. A meeting 1.5 hours in the future went through.

Kenneth - maybe we can walk through it at standup?

**Comment by kdflint** [comment]
Chrome: Date.parse("2016-02-02T20:30:00") gives a different epoch than other browsers.

Chrome gives an epoch that corresponds to 8:30 pm GMT
Other browsers give an epoch that corresponds to 8:30 pm local time. (CST in my case)

Handy tool: http://www.epochconverter.com/

Now, to solve this...

**Comment by kdflint** [comment]
In Chrome, "2016-02-02T20:30:00" is being interpreted by default in the UTC context. Other browsers use local time by default.

To be consistent, must pass an offset, like this:  "2016-02-02T20:30:00-0600"

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

Sigh. Offsets change through the year with daylight savingses.

An static offset table is now constructed and will be updated weekly using a cron job again pg database, which keeps wonderful track of these things.

OK to test this feature now against the current data set. Opening new issue #239 to cover the cron job implementation.

**Comment by kcavness** [comment]
Was able, in Chrome, to create a meeting 30 minutes in advance for an hour.
