### ISSUE TITLE
Change password sequence does not load local time zone into session

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#266]
This causes the current meeting list to be empty. Emergency Prod patch in place now hardcoding to "America/Chicago" when the session is generated by means of a password reset processor.

(Problem is that processor is not aware of local client prior to constructing the session. This was solved for Advantage.)

**Comment by kdflint** [comment]
To test:

Log in to NWM normally. Create a future meeting. Notice that your local timezone is displayed on the form.

Logout.

Invoke "Forgot password" and get the reset link to your Inbox.

Click the link and check that you can still see the event that you just created and also that your local timezone is displayed on an event add form

Prior to fix, when you accessed the app via the reset password link we were not setting your local timezone and as a side effect the future event list was not loading.

**Comment by gretchiesprite** [comment]
Works for me. Closing.
