### ISSUE TITLE
Line 761 in nexus.js fails in NWM context

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#267]
In NWM context we have not descr field... commented in PROD for the moment

**Comment by kdflint** [comment]
To test, add a future meeting in both NWM and ADV. For the ADV meeting, make the description multi-line (that is, put in a carriage return somewhere).

Form submission should work as expected.

Let Kathy know so she can confirm something in the database.

**Comment by gretchiesprite** [comment]
NWM works. I tried twice with ADV. I didn't see any new events pop up on the Events page, even after a reload.

**Comment by kdflint** [comment]
Kathy confirms this is working.
