### ISSUE TITLE
When a meeting is <= than 60 minutes in the future

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#287]
the page refreshes every 1 minute

**Comment by kdflint** [comment]
Test here

http://northbridgetech.org/dev/nexus/web/login.php?oid=12345678

Basic steps:

Create a meeting in one browser. In a different browser, hit the Guess Pass link.

Note - the meeting won't show as open until the conference room itself is OPEN.

**Comment by gretchiesprite** [comment]
When I try to create a meeting using that link, I get redirected here: http://northbridgetech.org/apps/nexus/web/login.php?oid=1c5b1ce5&mid=ecfdec75-cfe9-28f7-f957-0739070b5187

**Comment by kdflint** [comment]
Gretchen - is it possible that your session had expired? Right now there is no warning (the New Event form will show) but if you try to submit on an expired session it will kick you back to login screen. See #303 

I can't really explain why it went to the Guest Pass page. Nor can I explain errors in the log about that time from dev. Can you try again? I cannot reproduce.
