### ISSUE TITLE
When the meeting becomes open, the page creates an audible notification

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#288]

**Comment by kdflint** [comment]
For convenience, right now the refresh action plays a bouncey sound and the meeting open notification plays a different chimey sound.

The refresh sound will go away and the actual meeting open sound is not determined yet.

NOTE: You only get the meeting open sound when the conference room itself is open. You'll need two browser windows to pull this off.

**Comment by kcavness** [comment]
I have verified that fur future meetings that are set up, I get a notification that it's going to start.

**Comment by kcavness** [comment]
I have verified that I get a separate sort of sound when the conference room itself is open.
