### ISSUE TITLE
When a meeting moves to "Now" status, the page creates an audible notification

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#293]

**Comment by kcavness** [comment]
I have verified that I get a (different) audible notification when a meeting moves to "now" status.

**Comment by kdflint** [comment]
Question to everyone. On the Guest Pass, the page chimes when the page loads and the meeting is available right away (not needing a meeting state change to cause the chime)

Should we do the same inside Nexus Web Meet. That is, when this page loads and a meeting is running now, should we chime? Or only chime on a state change?

![screenshot from 2016-06-15 20 57 08](https://cloud.githubusercontent.com/assets/1907202/16103262/8d82cda2-333c-11e6-8537-86127a6e6e18.png)

**Comment by kdflint** [comment]
Kenneth - I don't think you tested this one. I think you tested #288

**Comment by kcavness** [comment]
I thought I was testing #293, in that I got a way different notification
sound when I was actually brought into the conference room, but I think I
was just misunderstanding the purpose of that acceptance criteria maybe?.

**Comment by kcavness** [comment]
I would not chime on a "meeting is immediately available" enter to the
site... they can see it right there on the page as it loads, right?

**Comment by kdflint** [comment]
I have implemented no chime when the meeting is open on the first page load.

State change will cause a chime.
