### ISSUE TITLE
Parentheses when editing show up as HTML entities

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#296]
![image](https://cloud.githubusercontent.com/assets/5615067/15489137/025fda76-2112-11e6-9dc5-a77df3496dc5.png)

**Comment by kdflint** [comment]
Trick: Setting the "value" of a textarea on a form should be done using element.innerHTML instead of element.value. This will automatically decode html entities.

**Comment by kcavness** [comment]
Parentheses now show up correctly!
