### ISSUE TITLE
Provide a language selection dropdown

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#313]
on the login and home page, with Spanish and English options

**Comment by kdflint** [comment]
Open for comment on placement. 

I am NOT fond of the placement on the Login screen. Makes a very simple screen suddenly busy, which I very much want to avoid. For this reason I'm thinking about not giving the language option on the Login screen - simply using the browser setting. Once in, they can change language if they want. Thoughts?

![screenshot from 2016-09-29 19 10 38](https://cloud.githubusercontent.com/assets/1907202/18976582/7a50c182-8678-11e6-931e-ba569eb109f6.png)

![screenshot from 2016-09-29 19 11 55](https://cloud.githubusercontent.com/assets/1907202/18976591/9fec6504-8678-11e6-86b5-a119f7b787be.png)

**Comment by kdflint** [comment]
I have decided to take my recommendation of leaving off the dropdown on the Login screen. Login screen renders according to browser preference with no user change possible.

**Comment by kcavness** [comment]
There's a little bit of irony in the dropdown saying "Site Language" ... in English.

**Comment by kcavness** [comment]
I logged in as myself, and chose the "Espanol" language item. It reloaded the page correctly and showed me "Hola Kenneth" as expected.

![image](https://cloud.githubusercontent.com/assets/5615067/19629398/666125cc-9929-11e6-8646-6478ea32b127.png)


I then changed to "English" and the page showed me "Hello Kenneth" as expected.

![image](https://cloud.githubusercontent.com/assets/5615067/19629406/76a58b58-9929-11e6-9485-6fe0dc508056.png)

I believe this can be accepted.

**Comment by kdflint** [comment]
​LOL. Awesome catch!

I suppose this should be dynamic.​

-- 


*Kathy D. Flint, CEO Northbridge Technology
Alliance**http://northbridgetech.org
<http://northbridgetech.org>*

*Status, power, and wealth are a function not of what you control but of
what you give away. ~Eric Raymond*
