### ISSUE TITLE
NWM Java add-on prompt

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#415]
![unnamed 9](https://cloud.githubusercontent.com/assets/1907202/24415588/8b0fb106-13a7-11e7-8c9a-d073f6de6e35.png)

**Comment by kdflint** [comment]
I can't make this happen and I've never seen it first-hand.

Has anyone else seen this occur?

**Comment by kswens1** [comment]
This pop up notification is due to the end users security protocol. The only to to avoid such a pop up is to have different security settings.

Closing this issue, as it is out of our control.
