### ISSUE TITLE
If FB sign-in matches > 1 user accounts, deny login

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#488]
Show error message in style of other authentication messages

**Comment by gretchiesprite** [comment]
Works as expected, can be passed.
<img width="888" alt="screen shot 2017-09-10 at 7 04 45 pm" src="https://user-images.githubusercontent.com/2071968/30254239-fe5ed052-965a-11e7-9c44-f1a09e2b6ecf.png">
