### ISSUE TITLE
Meetings created does not display when logged in from Facebook or LinkedIn

### ISSUE THREAD

**Issue by Hema-Nambi** [NorthBridge/nexus-community#509]
**Step 1:**  log in to a non admin account from "Facebook" or "LinkedIn"
**Step 2:** Create a meeting from future tile 

**Issue:** Created meeting does not appear on the future meetting tile 

**Note :** This issue does not occur when logged in with northbridge log in page

**Screen Prints:**
_Logged in with fb:_
![image](https://user-images.githubusercontent.com/30035025/31458665-c47e5d7a-ae8e-11e7-98ec-73ef8030efea.png)

Logged in with LI:
![image](https://user-images.githubusercontent.com/30035025/31458750-fb670300-ae8e-11e7-9a8e-da03594be98a.png)

Logged in with Northbridge log in:
![image](https://user-images.githubusercontent.com/30035025/31458785-1b8720b6-ae8f-11e7-9731-97097f4483c0.png)

**Comment by kdflint** [comment]
Fixed by getting the local timezone into the session with social media logins. (Prior they were being missed.)

**Comment by Hema-Nambi** [comment]
Defect retest and it works fine . Hence closing the defect .
