### ISSUE TITLE
Insert translations that have been obtained but are not implemented

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#517]
Jose V. gave us a batch of about 20 phrase translations that were never plugged in. These need to be configured

**Comment by kdflint** [comment]
New translations are implemented on the Room tab. 

I think we may already have a test running checking the change from "Hola" to "Hello" when the language dropdown is changed.

If so, we could close this Issue.... but I wonder...

Is it possible to have Selenium detect and/or change the browser's own locale settings and then running a display confirmation accordingly??

**Comment by Hema-Nambi** [comment]
I think it is possible . I have created a simple script in selenium to set locale to spanish and display our home page and it worked . Is this what is expected? Please refer the snapshot below.
![locale](https://user-images.githubusercontent.com/30035025/37007900-a29470a0-20ad-11e8-9620-ffb5630f2fbb.jpg)

**Comment by kdflint** [comment]
Yes, that's great! The test then will be if browser locale = x, display label = y.

I think we can drive the test right from the login screen so that cuts out the complication of logging in. 

Do you have a preference as to which display label we use? Maybe the Sign In button label?

**Comment by Hema-Nambi** [comment]
Yes . We can run the test from login screen and Sign In button label should work so will try with that .
