### ISSUE TITLE
Language doesnt change when logged out 

### ISSUE THREAD

**Issue by Hema-Nambi** [NorthBridge/nexus-community#524]
step 1:  Log into Nexus web meet 
Step 2: Change language to spanish 
Step 3: Now log out of Nexus immediately 

Language remains english in the log in page 

The same behaviour does not happen when logged out automatically due to inactivity . i.e, The language changes to spanish in the login page

**Comment by kdflint** [comment]
The login page takes it's language from the browser. On a user-initiated logout scenario, the login page will revert to the browser default even if the user changed the value manually inside the site session.

We could theoretically hang on to the user's language preference between sessions but I don't think it's important enough to warrant the work. If the browser's language is set to a certain value we can presume that the user understands that language enough to interact with a login screen. If the user happens to be someone different than the owner of the browser, well, oh well.
