### ISSUE TITLE
Submitting a Future meeting reservation gives error 

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#526]
When user is viewing in Spanish, the future meeting reservation form submit gives user a stringified code array dump, which indicates a form validation failure.

Form works when site is in English.

**Comment by kdflint** [comment]
Problem was in form validation. 

Updated javascript to use constant, because string literal was not reliable in a different language!

`if (time == null || time == "" || time.indexOf("Time") > -1) {`

becomes

`(time == null || time == "" || time.indexOf(TIME) > -1) {`

**Comment by Hema-Nambi** [comment]
This issue is fixed and hence closing it .
