### ISSUE TITLE
If user closes the confirmation modal

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#533]
by clicking the 'x', system simply logs them out

**Comment by kdflint** [comment]
Same access instructions as #536 .

To test: Simply close the modal using the upper right X button. You will be logged out.

**Comment by kdflint** [comment]
Ah ha - my description is bad. The "X" to test is the "X" on the popup window where you enter the confirmation code. You tested the "X" on the browser tab, if I'm reading you right...

![image](https://user-images.githubusercontent.com/1907202/46642074-baf59b00-cb3a-11e8-864b-b98f3af277ac.png)

Also you can get to the confirmation window without doing an actual enrollent by entering this in your browser location bar:

https://northbridgetech.org/dev/nexus/web/nexus.php#enrollmentConfirmation

**Comment by kcavness** [comment]
I was logged in as kcavness and given #535's instructions, triggered the confirmation modal. I clicked on the "X" at the upper right hand side of the modal and was logged out. I had to log back in, in order to continue.
