### ISSUE TITLE
Existing enrollment email will add a confirmation code

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#534]
For this release, it can simply be a static code (same for everyone)

**Comment by kdflint** [comment]
New enrollment email should show the static confirmation code 'JUSTICE'

**Comment by kswens1** [comment]
Combined with #537 
Received INVITATION e-mail Notification
Received CONFIRMATION e-mail with code
Successfully logged into Nexus
[#537 and #534.docx](https://github.com/NorthBridge/nexus-community/files/2434036/537.and.534.docx)

**Comment by kswens1** [comment]
Passed and test accepted
