### ISSUE TITLE
If user bypasses the modal by entering a browser url

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#535]
system re-presents the modal with every tab change. (This is good enough for now.)

**Comment by kdflint** [comment]
Get around the enrollment confirmation by entering hashtag #close in browser bar. Like this:

https://northbridgetech.org/dev/nexus/web/nexus.php#close

Modal will close. But you'll get it again anytime you click a different tab until you complete confirmation.

**Comment by kcavness** [comment]
Do I need to do this with a new user?

**Comment by kdf** [comment]
Yes. This will occur for a new user until the confirmation has been
successfully, uh, confirmed.

I can flip a status in the database however for an existing user if that
would be easier. Then an old user will act as if user has never confirmed.

Just let me know username.
