### ISSUE TITLE
When user confirms the email code successfully

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#536]
system updates their database record and their session. Modal disappears.

**Comment by kdflint** [comment]
This can be tested by manually triggering the confirmation modal. Navigate to 

https://northbridgetech.org/dev/nexus/web/nexus.php**#enrollmentConfirmation**

The correct code is 'JUSTICE'. Confirmation is case insensitive.

**Comment by kcavness** [comment]
I tried the following scenarios:

1. JUSTICE -- was successfully allowed to continue
2. justice -- was successfully allowed to continue
3. JUST ICE -- was told my confirmation code was incorrect and re-prompted with an error explanation
4. THIS IS A REALLY LONG CODE JUST TO SEE WHAT HAPPEN -- cut me off and correctly identified it as incorrect
