### ISSUE TITLE
After first login, system will present modal for user to confirm email

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#537]
We will allow a login (so, current flow unaltered). We present the modal though until the user confirms the code

**Comment by kdflint** [comment]
New enrollee should see the confirmation modal.

**Comment by kswens1** [comment]
Got a NOTIFICATION e-mail that instructed me to to follow a link for Nexus Web Conference.
Got a CONFIRMATION e-mail that provided me with a confirmation code
[#537.docx](https://github.com/NorthBridge/nexus-community/files/2434020/537.docx)
