### ISSUE TITLE
allow username to be re-used when the original...

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#541]
one is deactivated.

**Comment by Hema-Nambi** [comment]
1. when the enrolled user with the username , say "Tester1" is deleted.

2. Now when a new user is being enrolled , we cant use the same user name "Tester1" despite being deleted and there is no one with that user name .

![image](https://user-images.githubusercontent.com/30035025/46827085-b19c4680-cd65-11e8-9adf-2ee7e45b3944.png)

**Comment by kdflint** [comment]
To test:

Login to Nexus Web Meet in DEV at https://northbridgetech.org/dev/nexus/web/login.php?oid=12345678
 
Go to the Team tab
 
Add a new user to your own email address.

Log out of Nexus.
 
Find the enrollment email in your Inbox. Click the link to enroll, and enroll as usual. Note the username that you select

Log out of Nexus as the new user and back in as your original user
 
Go to the Team tab and delete the user that just enrolled and enroll a new user. (OK to go to the same email address.)
 
Back to your Inbox; enroll again.
 
This time, re-use the username that you used for the first enrollment. Before this change it would have been blocked. It should now allow.
