### ISSUE TITLE
The Guest Pass on individual meetings...

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#543]
is "widgetized." See Notes. The long url will no longer display on screen, only the Copy to Clipboard and View control.

**Comment by kdflint** [comment]
To test:

1. Create a meeting Now

2. Notice the new clipboard buttons

3. Click the Show

**Comment by kswens1** [comment]
navigated to the Nexus login ---> clicked the "Copy Pass to Clipboard" (even got a nice little pop up stating that I have copied the link.

 When I did a paste into Word Pad, the following populated:

https://northbridgetech.org/dev/nexus/web/login.php?oid=12345678&mid=6d2c2a73-a09a-3757-6bf4-5c7bab89ad35

I have visual, however, for some reason it is not longer letting me paste or attach; it let me do this before so not sure what I am doing wrong. I do consider the test a pass.

**Comment by kdflint** [comment]
Can we please do another round of testing? The last set of tests proved that the clipboard copy function worked on the Now meeting.

Now I have added the feature to Future Meetings and we need to prove that the clipboard copy function is correctly copying the unique pass for each meeting.

1. Make a new Future meeting. (There are probably a few already on the reservation list.)

2. For your new meeting, show the pass and copy the pass to the clipboard.

3. Is the pass you were shown in the popup the same as the pass you put on your clipboard? (They should be)

4. Repeat steps 2 and 3 for one of the other meetings on the reservaations list. 

5. Again, pick just one meeting and copy the pass to the clipboard. Notice the name of the meeting.

6. Log out of Nexus, then past the url into your browser url bar. Does the Meeting that appears have the correct name?

**Comment by kdflint** [comment]
Can we please do another round of testing? The last set of tests was good -- they proved that the clipboard copy function worked on the Now meeting.

Now I have added the feature to Future Meetings and we need to prove that the clipboard copy function is correctly copying the unique pass for each meeting when there are several guest passes on the page.

1. Make a new Future meeting. (There are probably a few already on the reservation list.)

2. For your new Future meeting, show the pass and copy the pass to the clipboard.

3. Is the pass you were shown in the popup the same as the pass you put on your clipboard? (They should be)

4. Repeat steps 2 and 3 for one of the other meetings on the reservations list. 

5. Once again, choose just one meeting and copy the pass to the clipboard. Notice the name of the meeting.

6. Log out of Nexus, then past the url into your browser url bar. Does the Meeting that appears onthe Guest login screen have the correct name? (That is, does the pass take you to the right meeting?)

**Comment by kswens1** [comment]
I created a future meeting (for today at 8:30; and there was no button, just the long url to the meeting address)
