### ISSUE TITLE
Enrollment emails sometimes take a long time to be delivered

### ISSUE THREAD

**Issue by Hema-Nambi** [NorthBridge/nexus-community#545]
- Enroll a new user to nexus web meet .

- Enrollment email for the new enrolled user takes a long time to receive .

example : 
New user was enrolled in web meet at 5.10 pm 
mail to the new enrolled user was received at 7.56 pm

Also on clicking on the link on the enrollment email , nexus log in page gets opened instead of the enrollment page 
![enrollment issue](https://user-images.githubusercontent.com/30035025/46824317-734f5900-cd5e-11e8-9373-89b17320fc63.JPG)

**Comment by kdflint** [comment]
I think the second problem, where the link sent user to the login page, we resolved. Somehow the enrollment had already been successful and the expected behavior in that case is that user goes to login page. Does that sound right, Hema?

**Comment by kdflint** [comment]
On slow emails, I have opened a ticket with our web host. I will let folks know how this research goes. (We probably will not have an answer before our sprint delivery is due.)

It reads like this:

> Occasionally it takes a very long time for my clients to receive email generated from my web site, which is running under a shared hosting account.
> 
> Do you have any suggestions for ways to diagnose whether or not my web server is a part of the problem? For instance, does CPanel offer any email delivery logs for viewing?
> 
> I know that email delivery is a very complicated networking topic and that slowdowns can occur in many places along the delivery network that have nothing to do with the originating server performance. Just looking for any research tools you can suggest related to my web server.

**Comment by kdflint** [comment]
Update: Got this reply from tech support. Hema - maybe you can try another enrollment and see if you can get a slow one?

> Hello,
> 
> Unfortunately, there's no simple way of viewing this within cPanel. We can view the logs manually though. If you provide an example email including the sending and receiving address as well as subject and time sent, we may review if there are any potential issues on our side.

**Comment by Hema-Nambi** [comment]
I have recreated the issue : 

Enrolled email id : testuser21111996@gmail.com
Enrollment time : 8.50 pm
Enrollment date : November 8 , 2018

![image](https://user-images.githubusercontent.com/30035025/48278364-46ed3200-e41b-11e8-810d-afe344f07185.png)

The enrollment mail has not yet received
Day 2 :  November 9, 2018

![image](https://user-images.githubusercontent.com/30035025/48278401-5ec4b600-e41b-11e8-9ba7-ea5f506c8c14.png)

**Comment by kdflint** [comment]
I have update my support ticket with this instance. Thanks Hema!

We'll see what they come back with.

Kathy

**Comment by kdflint** [comment]
Tech support results. I'm not sure what to do next. Any ideas? Maybe to do a bunch of enrollments to many different emails and see how widespread this problem is?

> The logs show the mail successfully sent at 8:52 PM, as expected. Please refer to the below and let us know if you have any further questions:
> 
> 2018-11-08 20:52:34 1gKvyL-0066XW-7n => testuser21111996@gmail.com R=send_via_mailchannels T=mailchannels_smtp H=smtp.mailchannels.net [52.10.98.122] X=TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256 CV=yes A=mailchannels_login C="250 2.0.0 Ok: queued as 4897642181"
> 2018-11-08 20:52:34 1gKvyL-0066XW-7n Completed

**Comment by kdflint** [comment]
We have decided to do some broader testing on this to see if we can find a pattern for the slow emails. We need to do an enrollment to a bunch of email domains. (The domain is the part after the @ sign.)

I can do a test to hotmail.com, yahoo.com, gmail.com, and eths202.org

What can others add? Ok to duplicate domains but the more variety we get the better.

So to test, [in DEV](http://northbridgetech.org/dev/nexus/web/login.php?oid=), go to the TEAM tab and create an enrollment. Send it to your test email. Do one for every email address you can think of. Keep track of roughly how long it takes for the enrollment email to appear in your Inbox.

No need to actually complete the enrollment.

You can record your results here in this issue.

**Comment by kdflint** [comment]
Based on my results I have a hunch that Gmail is throttling these messages when multiples are sent to an account held by the same person.

============

Kathy's results:

northbridge.test@hotmail.com: < 1 minute, went to Junk

northbridge.test@yahoo.com: < 1 minute

ksflint@comcast.net: < 1 minute

acflint@eths202.org: < 1 minute

kathy.d.flint@gmail.com: 
  first one: < 1 minute
  second one: > 10 minutes, still waiting
  third one: > 10 minutes, still waiting

**Comment by Hema-Nambi** [comment]
Hema's test results:

1. testuser21111996@gmail.com :  < 1 minute, went to junk

2. testuser24@hotmail.com : < 1 minute , went to junk

3. testuser21111996@gmail.com :  40 minutes 

4. hemnam24@gmail.com:  still the mail has not come (its been aprox 4 hours)

I guess there is some issue with gmail domain

**Comment by kdflint** [comment]
Gmail is clearly throttling email delivery. This specific situation should rarely impact a real-life enrollee. Given that discovery, in combination with our support procedures of following up with new enrollees if they have not activated in 24 hours, we will "solve" this by upgrading to a fuller featured messaging framework. We need to do this for several other reasons anyway.

This has been added to the backlog for prioritization by Product Owner.

Reference link: https://pepipost.com/blog/email-throttling/
