### ISSUE TITLE
User gets logged out of conference room automatically in a few minutes of joining the meeting

### ISSUE THREAD

**Issue by Hema-Nambi** [NorthBridge/nexus-community#546]
-  User was getting logged out of the  conference room automatically in a few minutes of joining the meeting.
under the following set up : 
         OS : Windows 10
         Browser : Chrome
        Internet connection : WiFi

**Comment by kdflint** [comment]
There are two possible reasons that I know about for this:

1. The internet connection is not very strong. If this is the case, hopefully the system tech check on the meeting will show a caution symbol. Hema - how strong is your wifi? I'm betting that is not the problem, but worth checking.

2. I have experienced this when my laptop rotates between internet connections, which sometimes it does all by itself. This happens to me when I am on a wired network and also on a wireless. I always disable the wireless and that solves it for me. 

One way to test if that is what is happening is to join the room, then change your connection source. Do you get logged out - probably yes. Could this be the issue in general, Hema?

**Comment by Hema-Nambi** [comment]
Tested this issue by 
1. Creating a meeting 
2. Joined the newly created meeting 
3. Changed the internet source . Still it worked . Session didn't get logged out .

I guess the issue was with poor wifi connecting .
Because the wifi connection is very strong now and the issue has been resolved .
And I think this issue is good to be closed
