### ISSUE TITLE
Hovering mouse over the "copy pass to clipboard button" shows message "copied " even before clicking it 

### ISSUE THREAD

**Issue by Hema-Nambi** [NorthBridge/nexus-community#547]
1. Create a meeting Now

2. Notice the new clipboard buttons

3. Hovering mouse over the "copy pass to clipboard button" 

Issue: you will notice "copied" message even before clicking the button

**Comment by Hema-Nambi** [comment]
![image](https://user-images.githubusercontent.com/30035025/47876094-c614b180-ddee-11e8-9752-3fa0c265d40b.png)

**Comment by kdflint** [comment]
Now hovering over the button will show "Click to copy" and actually clicking it will show "Copied!"

Please confirm.

**Comment by kdflint** [comment]
Ta-da. Try now.

**Comment by kswens1** [comment]
Wonderful!
When I click on the "Copy Pass to Clipboard" I get the "Copied!" pop up, when I click the "Copy Pass to Clipboard" for the future meeting and go back to hover over the current meeting, "click to copy" pop up is appropriately appearing under the current meeting and "Copied!" pop up appropriately appears for the future. I consider this a pass. I got the following links when I copied
**Hema Test2:**
https://northbridgetech.org/dev/nexus/web/login.php?oid=12345678&mid=8bfa6a1a-f6a6-cb0c-ccef-4973d37f1473
**Future 2:**
https://northbridgetech.org/dev/nexus/web/login.php?oid=12345678&mid=5e45f83f-4408-a447-fe0f-3141d23ae366
**Hema Test:**
https://northbridgetech.org/dev/nexus/web/login.php?oid=12345678&mid=eb90899c-c459-2a84-f51c-a3411d33ba8a
