### ISSUE TITLE
Summarize successes

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#567]

**Comment by kdflint** [comment]
Seeing how to joining a meeting caused no problems for anyone! That was the major goal of the testing. In one case the meeting itself did not load, but that was after the user joined.

In one case the user couldn't hear but that was because the second user did not have a mic.

"This is a very user friendly and intuitive application – it walks you right through what you need to do, and the big shadowed buttons leave no room for doubt on where a user should click."

**Comment by kswens1** [comment]
I agree with your findings
