### ISSUE TITLE
Summarize action items

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#568]
and move to backlog

**Comment by kdflint** [comment]
One user locked out due to Flash installation on work computer. - Flash dependency goes away in April :)

"I would rather use jabber with a headset." - not sure what the options are

"The big blue button on top of the presentation kind of makes you think you have to click on it." - Try to upload a customized default presentation slide - one that gets rid of BigBlueButton reference and mentions Nexus Web Meet instead.

"Is there a way to turn off the write ability" - not sure what the options are

"The talk feature would probably be better if someone was using a headset with a microphone due to if you talk just in your computer you may get background noise." - find ways to highlight how important ear buds are.

**Comment by kdflint** [comment]
[Test Scenarios Cycle 1 01-2019.rtf - Jeanie.pdf](https://github.com/NorthBridge/nexus-community/files/2975963/Test.Scenarios.Cycle.1.01-2019.rtf.-.Jeanie.pdf)
[Test Scenarios Cycle 1 01-2019 Eileen Caesar feedback.pdf](https://github.com/NorthBridge/nexus-community/files/2975964/Test.Scenarios.Cycle.1.01-2019.Eileen.Caesar.feedback.pdf)
[Test Scenarios Cycle 1 01-2019 Nancys feedback.pdf](https://github.com/NorthBridge/nexus-community/files/2975965/Test.Scenarios.Cycle.1.01-2019.Nancys.feedback.pdf)

**Comment by kswens1** [comment]
"I would rather use jabber with a headset." - not sure what the options are - this is internal functionality on the users end. (using a softphone when testing)

I agree with your problem statements
