### ISSUE TITLE
Improve input validation on enrollment, user profile forms

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#60]
On enrollment and/or user profile, as applicable:

Disallow dupe username
Disallow username = password
Put min/max length on password and username
Improve color and positioning of validation error messages
Make user input sticky for valid fields (and do this with directory searching while at it!)

**Comment by gretchiesprite** [comment]
If I enter the same text for password and username, the error message tells me to enter valid matching passwords, not that my password can't be the same as my username. I get the same message if I enter passwords that are too short. Do we want to change the error message?

**Comment by kdflint** [comment]
Message changed :)

Enter "asdfas1df" for all three fields and you should see a different message now.
